### ISSUE TITLE
Update identifier for some "Is Dataset" option

### ISSUE THREAD

**Issue by roomthily** [b-cube/semantics-preprocessing#14]
In identifier.py, add some widget to identify if the XML blob includes some dataset-level metadata (since we have the service-level metadata check).

This could just be for metrics purposes and not truly required for any pipelining.

**Comment by roomthily** [comment]
Update identifier.py for the parser->triplestore generation (very explicit service parsing) and update the quick_identifier.py script for the larger set of service identification for metrics.

**Comment by roomthily** [comment]
See #13 for tag normalization in this.

**Comment by roomthily** [comment]
See the lib/configs/identifiers.yaml for the current structure (based on the prioritized list)

```
protocols:
  - name: OpenSearch
    filters:
      ors:
        - type: simple
          object: content
          value: 'http://a9.com/-/spec/opensearch/1.1/'
    services: 
      - name: 'OpenSearchDescription'
        filters: 
          ors:
            - type: simple
              object: content
              value: 'OpenSearchDescription'
```

with string.contains and/or a little regex with python magic.
